// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOVzmh_jcGAC2-4xmk8KomDKX4WTUb3ko',
    appId: '1:447970992345:web:f43720aafcd3b13a669ec8',
    messagingSenderId: '447970992345',
    projectId: 'bydeliverymovel',
    authDomain: 'bydeliverymovel.firebaseapp.com',
    storageBucket: 'bydeliverymovel.appspot.com',
    measurementId: 'G-W5877ZBS96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjoDjZvObhn6UQ7jV2OHQhXiImM_RRafw',
    appId: '1:447970992345:android:cd85867b7ed92184669ec8',
    messagingSenderId: '447970992345',
    projectId: 'bydeliverymovel',
    storageBucket: 'bydeliverymovel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqmgyzSrH7ZgfJowxDxmmdY5QLPGCe85k',
    appId: '1:447970992345:ios:9aa205d27f059d0a669ec8',
    messagingSenderId: '447970992345',
    projectId: 'bydeliverymovel',
    storageBucket: 'bydeliverymovel.appspot.com',
    iosClientId: '447970992345-95f44cgc927tjvn7l06polc90qrp048b.apps.googleusercontent.com',
    iosBundleId: 'com.example.bydelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqmgyzSrH7ZgfJowxDxmmdY5QLPGCe85k',
    appId: '1:447970992345:ios:05dee1e39da5aa51669ec8',
    messagingSenderId: '447970992345',
    projectId: 'bydeliverymovel',
    storageBucket: 'bydeliverymovel.appspot.com',
    iosClientId: '447970992345-bmnck0k38f26i6vi3su6tf7q5cnf2l3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.bydelivery.RunnerTests',
  );
}
